version: '3'

services:

  mdb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sokobanpass # mysql password
    ports:
      - 3306:3306
    volumes:
      - /Users/sokoban/mysql:/var/lib/mysql # 호스트의 디스크 공간으로 맵핑

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 # http://127.0.0.1:8080